# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'rails', '~> 7.0', '>= 7.0.1'

gem 'rainbow', '~> 3.1', '>= 3.1.1'
gem 'tty-command', '~> 0.10.1'
